### ISSUE TITLE
Run on entire directory?

### ISSUE THREAD

**Issue by 19peaches** [phpfmt/fmt#101]
Is there a way to run this on an entire directory in Sublime Text 3? I didn't see anything in the docs.

Thanks.

**Comment by ccirello** [comment]
Hi, unfortunately there is not such support. Personally, whenever I need to do this bulk operation, I just run fmt.phar straight from CLI. Actually, it is safer as you can trap its output into a file for later inspection - and also can enable or disable the backup flag. So I strongly advise you to use the fmt.phar straight from CLI.
