### ISSUE TITLE
Isn't correct passes

### ISSUE THREAD

**Issue by Myrai** [phpfmt/fmt#102]
phpfmt (php version):
PHP 5.6.17 (cli) (built: Jan  6 2016 13:28:38) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

phpfmt (php tokenizer) found

phpfmt (fmt.phar version):
C:\Users\Nekt\AppData\Roaming\Sublime Text 3\Packages\phpfmt\fmt.phar 19.2.1

PHP 5.5 compatibility mode: False

cmd_fmt:  ['D:/php/php.exe', 'C:\\Users\\Nekt\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\fmt.phar', '--config=C:\\Users\\Nekt\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\php.tools.ini', '--psr2', '--indent_with_space=4', '--enable_auto_align', '--smart_linebreak_after_curly', '-v', '-o=-', '-']
p:
 0
err:
 Used passes: EliminateDuplicatedEmptyLines, RTrim, PSR2IndentWithSpace, LeftAlignComment, PSR2AlignObjOp, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2CurlyOpenNextLine, PSR2LnAfterNamespace, PSR2KeywordsLowerCase, ReindentEqual, Reindent, ReindentObjOps, AlignDoubleArrow, AlignEquals, ReindentSwitchBlocks, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderAndRemoveUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine

**Comment by ccirello** [comment]
@Myrai Please provide more context. A piece of PHP code that's failing, and the content of Sublime Text's configuration files.

**Comment by Myrai** [comment]
default
{
"version": 4,
// "php_bin":"/usr/local/bin/php",
// "format_on_save":true,
"option": "value"
}
user
{
	"debug": true,
	"enable_auto_align": true,
	"indent_with_space": 4,
	"php_bin": "D:/php/php.exe",
	"psr2": true,
	"version": 1
}
code
http://pastebin.com/dDSrcSQm

**Comment by ccirello** [comment]
Could you describe the problem you are facing?

**Comment by Myrai** [comment]
ctrl+f11 
and show this in console(all version up):
err:
 Used passes: EliminateDuplicatedEmptyLines, RTrim, PSR2IndentWithSpace, LeftAlignComment, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2CurlyOpenNextLine, PSR2LnAfterNamespace, PSR2KeywordsLowerCase, ReindentEqual, Reindent, ReindentObjOps, ReindentSwitchBlocks, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderAndRemoveUseClauses, AutoImportPass, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine

**Comment by ccirello** [comment]
This message seems perfectly fine. It says it applied all these passes - you can see the core passes and PSR2 (the ones activated with `--psr2`)

What is the expected output you want in the buffer?

**Comment by Myrai** [comment]
I though "err: ..." but "used passes.." this output compiler, because "err" haven;t ".".
excuse me.

**Comment by ccirello** [comment]
No problem.
