### ISSUE TITLE
Per-project configuration

### ISSUE THREAD

**Issue by kokokurak** [phpfmt/fmt#104]
Is it possible to set phpfmt settings on project basis? I think SublimeText doesn't allow such thing natively, but is there any workaround for phpfmt?

I'm having several Laravel projects, some WordPress ones and others, each of them follow different standards. What workflow is recommended to make convenient use of phpfmt in such case? For now, I'm using it only for Laravel and disable the plugin entirely when I work on other tools. It's no fun though.

**Comment by ccirello** [comment]
Have you considered using `https://github.com/phpfmt/fmt/blob/master/src/.phpfmt.ini` files?

**Comment by kokokurak** [comment]
How do I tell Sublime to use the file as phpfmt config? And also, does it merge with user settings or overwrites them all?

**Comment by ccirello** [comment]
After you toggle `phpfmt: look for .php.tools.ini`, the ST3 plugin will look for the file in the current directory and its parents. The best practice is to empty your user configuration file and let it read from the ini file.

**Comment by kokokurak** [comment]
I added `.phpfmt.ini` file and toggled `phpfmt: look for .php.tools.ini`, but it doesn't do anything. Should I rename it to `.php.tools.ini`? I think the behavior was changed to use `.phpfmt.ini`, right?

**Comment by ccirello** [comment]
it shouldn't matter because it is detected by the plugin and passed as parameter to the formatter. Open a bug in phpfmt/sublime-phpfmt with the debug flag turned on, and its output in the console, to be sure what's being passed to the fmt.phar

**Comment by kokokurak** [comment]
I opened #105
