### ISSUE TITLE
PHPFMT not working on build 3103

### ISSUE THREAD

**Issue by Ganganation** [phpfmt/fmt#108]
After updating to Sublime build 3103 phpfmt is not available anymore.

**Comment by ccirello** [comment]
Consider upgrading to build #3104 or newer.

**Comment by Ganganation** [comment]
Build #3103 is the latest.

**Comment by ccirello** [comment]
![image](https://cloud.githubusercontent.com/assets/138827/13155741/fe2e2d8c-d633-11e5-9be1-3fb57a5e260c.png)

That's what I get.

Could you please enable the debug flag and paste console's output here?

**Comment by Ganganation** [comment]
My bad. After a restart (build #3103) phpfmt was working again!
Stupid. Never thought of restarting.

BTW I use the stable version.

Thanks for you help! You may close it now ;)
