### ISSUE TITLE
Issue with NewLineBeforeReturn when method only contains return

### ISSUE THREAD

**Issue by mdio** [phpfmt/fmt#109]
Sorry that I can't provide a pull request since I'm not that good at working with tokens, yet.
I hope that the failing test case can help:
in:
```php
function a(){
    return 'a';
}
```

expected out:
```php
function a(){
    return 'a';
}
```

actual out:
```php
function a(){
    
    return 'a';
}
```

**Comment by ccirello** [comment]
Thanks for reporting this. We are going to fix it ASAP.

**Comment by ccirello** [comment]
Please, upgrade to https://github.com/phpfmt/fmt/releases/tag/19.5.1

**Comment by mdio** [comment]
Did so and can confirm it works with 19.5.1.
Thanks for the fast fix!
