### ISSUE TITLE
Issue with NewLineBeforeReturn in switch blocks

### ISSUE THREAD

**Issue by jaakon** [phpfmt/fmt#110]
I have found an issue similar to #109 but in switch blocks:

source & expected result
```php
switch ($mode) {
	case 'day':
		return $date;
	case 'week':
		return static::getLastOfWeek($date);
	case 'month':
		return static::getLastOfMonth($date);
	case 'year':
		return static::getLastOfYear($date);
}
```

actual result
```php
switch ($mode) {
	case 'day':

		return $date;
	case 'week':

		return static::getLastOfWeek($date);
	case 'month':

		return static::getLastOfMonth($date);
	case 'year':

		return static::getLastOfYear($date);
}
```

This behavior violates a CodeSniffer rule (PSR2.ControlStructures.SwitchDeclaration.BodyOnNextLineCASE) but I don't know whether it's relevant for phpfmt or not.

**Comment by ccirello** [comment]
It seems a legit bug.

**Comment by ccirello** [comment]
Please, upgrade to https://github.com/phpfmt/fmt/releases/tag/19.5.2

**Comment by jaakon** [comment]
It works like a charm, thank you.

Incredibly fast response...!
