### ISSUE TITLE
newline inserted after closing curly brace in one-line template code

### ISSUE THREAD

**Issue by slang800** [phpfmt/fmt#113]
```php
<?php if (3 > 2) {?>
    <a href="http://example.com">a link</a>
<?php }?>
```

...gets converted into this:

```php
<?php if (3 > 2) {?>
    <a href="http://example.com">a link</a>
<?php }
?>
```

...which seems wrong

**Comment by ccirello** [comment]
I need more context. Could you please share the command call you are using? Also keep in mind phpfmt was never meant to be used in cases PHP is mixed with something else. Check this: https://github.com/phpfmt/sublime-phpfmt/issues/126#issuecomment-105162647

**Comment by slang800** [comment]
I just installed it via composer (resulting in version `19.6.0` being installed) and I ran it with `php vendor/phpfmt/fmt/fmt.phar ./test.php`

**Comment by ccirello** [comment]
please upgrade to https://github.com/phpfmt/fmt/releases/tag/19.6.1 and try again.

**Comment by slang800** [comment]
Wow, that was quick! And that update fixed at least half of the issues in my code-base. I'll post separate issues for the rest of them.
