### ISSUE TITLE
Minor array align problem

### ISSUE THREAD

**Issue by KKSzymanowski** [phpfmt/fmt#116]
This issue is regarding Sublime Text 3 plugin, but adding issues there has been disabled, so I'm writing here.

When an array key contains non-latin characters(diacritics), plugins recognizes them as two characters and aligns the T_DOUBLE_ARROW(=>) one character to the left regarding other lines.

I mainly use UTF-8 but it happens also with Central European Encoding (ISO 8859-2).

Screenshot:
![align](https://cloud.githubusercontent.com/assets/13980973/13784527/ecb981a4-eacf-11e5-90d2-619982170129.png)

Obviously I can live with this but it's getting kind of annoying especially when there are multiple diacritics in an array key.

**Comment by ccirello** [comment]
Could you please provide with a gist of the failing code for debugging purposes?

**Comment by KKSzymanowski** [comment]
I'm not an advanced user of GitHub but I hope this is what you meant:

https://gist.github.com/KKSzymanowski/d5a57405be2ced91eb4d

**Comment by ccirello** [comment]
@KKSzymanowski It didn't fail for me.

![image](https://cloud.githubusercontent.com/assets/138827/13789260/72225b14-eae3-11e5-8c33-2c42b48f0296.png)

**Comment by ccirello** [comment]
Consider reopening this bug report when you have a repeatable example.

**Comment by KKSzymanowski** [comment]
What version of Sublime and phpfmt do you use?
Mine is Sublime Text 3, build 3103 and phpfmt v10.3.0(automatically installed from package manager).
What is your phpfmt configuration file?

**Comment by ccirello** [comment]
The same. As yours. For this test, I used:

```
{
	"format_on_save": true,
	"passes":
	[

		"AlignDoubleArrow"
	],
	"php_bin": "/usr/local/bin/php",
}
```

**Comment by KKSzymanowski** [comment]
Ok. I have found it. I had the option `"php55compat": true` in my config file. It was from back when I used PHP 5 but I have now installed PHP 7 and without PHP 5 compatibility it works perfectly.
Also, it only works properly with the `passes` option as in your config file.

Thank you very much for your support.
