### ISSUE TITLE
fix auto semicolon inside array

### ISSUE THREAD

**Issue by ctf0** [phpfmt/fmt#118]
currently if u have an array with missing comma, the auto semicolon setting will put a semicolon at the end of the array item which will also cuz other problems in the following code.

**Comment by ccirello** [comment]
I couldn't understand what you meant. Please, provide a code example.

**Comment by ccirello** [comment]
After some effort, I managed to understand what you meant. It is not a bug. It will add a semicolon if the last token in the line is not a terminator.

**Comment by ctf0** [comment]
take the below ex
```php
$rules = [
            'title'       => 'required|unique:posts|max:255',
            'description' => 'required',
            'address'     => 'required',
            'phone'       => 'required|digits_between:8,11',
            'price'       => 'required|numeric'
            'video_link'  => 'url',
        ];
```

the price item doesnt have a comma, so when u save it will add a semicolon not a comma :)

**Comment by ccirello** [comment]
the autosemicolon is not a replacement for syntax mistakes. It will just inject the semicolon when all else is still valid code.

**Comment by ctf0** [comment]
that exactly what i mean, but by any mean u cant have a semicolon in an array, only comma
