### ISSUE TITLE
Sort "use" statements by length only

### ISSUE THREAD

**Issue by hughsaffar** [phpfmt/fmt#125]
I just wanted to know how is it possible to sort the use statements by length ony?

**Comment by ccirello** [comment]
Have you tried using the pass `SortUseNameSpace`?

**Comment by hughsaffar** [comment]
Matter of fact no :) So, in Sublime Text it would be:
```
"sort_use_namespace": true
```

**Comment by ccirello** [comment]
Use the command palette `phpfmt: toggle additional transformations`, then you choose `SortUseNameSpace`.

**Comment by hughsaffar** [comment]
Thanks :+1:
