### ISSUE TITLE
T_ELSE and T_ELSEIF on newlines

### ISSUE THREAD

**Issue by rhabbachi** [phpfmt/fmt#126]
### Description:
First of all thanks for this app as it made my easier.

I'm trying to to the phpfmt to adhere to the [Drupal coding standards](https://www.drupal.org/coding-standards). Most of those requirements are supported in phpfmt but one major missing piece is the support for newlines for `else` and `elseif` (https://www.drupal.org/coding-standards#controlstruct). Any plans on adding support for this style?

Thanks! 

###Failing code:
N/A

###Expected result:
N/A

###Actual result:
N/A

###Your configuration:
```
$phpfmt --no-backup --smart_linebreak_after_curly --passes=RestoreComments,MergeElseIf,ReindentSwitchBlocks,PrettyPrintDocBlocks,PHPDocTypesToFunctionTypehint --indent_with_space=2
```

**Comment by ccirello** [comment]
> Any plans on adding support for this style?

No. Patches are welcome, though.
