### ISSUE TITLE
Prevent the default behaviour of removing unused namespaces after formatting..

### ISSUE THREAD

**Issue by jagroop** [phpfmt/fmt#127]
Hello Sir,
 First of all thanks for this awesome package i love it :heart:   ,
i am working on laravel so i am using bunch of namespaces
but the thing is after typing bunch of lines of code when i try to format my code using this package .. it removes unused namespaces .. is there anyway to prevent this default behaviour  ..
 

Example:
```
<?php
namespace App;
use One;
use AnotherOne;
class Example extends Controller {
 One::action([...]);
}
```

After Formatting:
```
<?php
namespace App;
use One;
-- removed because not in Use --
class Example extends Controller {
 One::action([...]);
}
```

**Comment by ccirello** [comment]
I really don't understand why Laravel people want to keep unused imports in their source code. You should try using php.oracle for the autoimport, so this would be a problem anymore.

Anyway, just use `--exclude` in the CLI call with `OnlyOrderUseClauses` and `OrderAndRemoveUseClauses` and your imports will be kept intact.
