### ISSUE TITLE
Problems running with Windows 10 - utf8 error

### ISSUE THREAD

**Issue by victorwbuzz** [phpfmt/fmt#133]
Configured with php 7.0.0
I'm using Windows 10

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\Avell\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 755, in run
    src = dofmt(self, self.view, None, src, True)
  File "C:\Users\Avell\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 125, in dofmt
    print_debug("phpfmt (php_ver) out:\n", res.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 102: invalid continuation byte

PHPFMT Settings:
{
	"php_bin": "C:/laragon/bin/php/php-7.0.0/php.exe",
	"psr2": true,
	"version": 1
}

**Comment by ccirello** [comment]
Please confirm your ST version. I don't have a Windows boxy right now. I plan to fix it ASAP.

**Comment by ccirello** [comment]
@victorwbuzz I need more context - I can't reproduce this issue.

**Comment by victorwbuzz** [comment]
@ccirello 
Sublime Text 3103.
I was using phpfmt with php 5.6 and got message of upgrade. So installed php 7.0.0 that came with Laragon.

Addict: tried to perform a clean installation with new sublime only with php-fmt. Same error.

**Comment by victorwbuzz** [comment]
Try to Reproduce with this steps:
- Download and install Laragon
- Point php-fmt settings to php 7 bin
- Try to format some file.

**Comment by ccirello** [comment]
what happens when you use the Official PHP 7?

**Comment by victorwbuzz** [comment]
Tried too. Same thing.

**Comment by victorwbuzz** [comment]
command "php fmt.phar" works

**Comment by Waleedviews** [comment]
Same issue. is it possible to use php 5.5 with phpfmt ?
in the latest update** phpfmt: toggle PHP 5.5 compatibility mode** is removed. So how can i use compatible mood.

**Comment by ccirello** [comment]
>  is it possible to use php 5.5 with phpfmt ?

You can format php 5.5 code - but you need to install php 7.0 to run the phpfmt engine. Install a standalone PHP 7.0 binary and point the plugin to the place you've installed it.

**Comment by jdanosborne** [comment]
Any pointers as to how to install PHP 7 standalone on Ubuntu? All the links I've found e.g. http://askubuntu.com/questions/705880/how-to-install-php-7 refer to removing PHP 5 which I need to keep for runtime. I've downloaded php-7.0.5.tar.bz2 but am unclear quite what to do with it.

TIA

Dan

**Comment by ccirello** [comment]
@jdanosborne, follow these instructions http://php.net/manual/en/install.unix.php

**Comment by ccirello** [comment]
@jdanosborne this could be useful too: https://github.com/Linuxbrew/linuxbrew

**Comment by ccirello** [comment]
@victorwbuzz please install a newer ST3 version. This might be helpful https://github.com/phpfmt/fmt/issues/108
