### ISSUE TITLE
New release not working in Sublime Text 3 with PHP 5.6.  What should I do?

### ISSUE THREAD

**Issue by leandromatos** [phpfmt/fmt#134]
I would like to continue with PHP 5.6, but the new version says I need PHP 7 to use plugin in Sublime Text 3. What should I do?

**Comment by ccirello** [comment]
Install a standalone PHP 7.0 version locally. You can keep working with 5.6. The fmt.phar knows how to handle old versions of PHP code, the PHP 7.0 is just for the engine.
