### ISSUE TITLE
PHP 7.0 or newer is required?

### ISSUE THREAD

**Issue by Bearsuny** [phpfmt/fmt#135]
After re-install phpfmt, it requires php-7.0 or newer, but I only have php 5.6, why it requires php 7.0 or newer??

**Comment by ccirello** [comment]
For several reasons. Among them, the need for static typing, speed and sticking to latest stable. You can, however, use fmt.phar (or the ST plugin) to formar old versions PHP code. PHP 7.0 is just for the engine.
