### ISSUE TITLE
Disable automatic left trim

### ISSUE THREAD

**Issue by vichenze** [phpfmt/fmt#138]
Is there a way to disable the left trim on a php line ?

For exemple, I have this code:
```
<div class="carousel-wrapper">
	<ul class="carousel-livre" >
	<?php
		$k = 1;
		while ($liv = $liste_liv->suivant())
		{
			echo '<li>
					<a href="#click">
						<img src="' . $liv->getImg(true) . '" alt=""  />
					</a>
				</li>';
		}
	?>
	</ul>
</div>
```
which is completely correct for me.

And when phpfmt gives this:
```
<div class="carousel-wrapper">
	<ul class="carousel-livre" >
	<?php
$k = 1;
while ($liv = $liste_liv->suivant())
{
	echo '<li>
			<a href="#click">
				<img src="' . $liv->getImg(true) . '" alt=""  />
			</a>
		</li>';
}
?>
	</ul>
</div>
```

The original code should be untouched.

**Comment by ccirello** [comment]
phpfmt is a PHP formatter. Not a mixed-code formatter. this request is out of scope.

**Comment by vichenze** [comment]
Well my example wasn't may be the best one, but I have same issue on PHP only files.

```
<?php

	$q = !empty($_GET['q']) ? $_GET['q'] : null;

	if (!empty($q))
	{
		...
	}

?>
```

Isn't there a way to keep the first tab / indentation?

**Comment by ccirello** [comment]
> Isn't there a way to keep the first tab / indentation?

why would you want to do it?

**Comment by vichenze** [comment]
I find it easier to read when there is some space at the beginning of the line, and when the code is not directly near the line number.
But I suppose this is only personal...

**Comment by leandromatos** [comment]
I have the same problem, in the previous release works normally.

**Comment by ccirello** [comment]
@leandromatos which version?

**Comment by leandromatos** [comment]
@ccirello Before 20.0.0.

**Comment by ccirello** [comment]
@leandromatos open a new ticket, filling up the form and providing as much context as possible. Preferably running both versions.
