### ISSUE TITLE
Closing </pre> tag deleted from block comment on format now

### ISSUE THREAD

**Issue by aeyachts99** [phpfmt/fmt#139]
Description:
Running format now on code inside a block comment that includes a closing </pre> tag, deletes the closing </pre> tag.

Failing code:
```
/*echo '<pre>';
	print_r($my_array);
	echo '</pre>';*/
```

Expected result:
```
/*echo '<pre>';
	print_r($my_array);
	echo '</pre>';*/
```

Actual result:
```/*echo '<pre>';
		print_r($my_array);
	*/

```

Your configuration:
```
![screen shot 2016-04-29 at 13 57 28](https://cloud.githubusercontent.com/assets/12847913/14916574/65cd1c6c-0e12-11e6-8946-b43a66dfc601.png)
![screen shot 2016-04-29 at 13 57 41](https://cloud.githubusercontent.com/assets/12847913/14916575/65f4b97a-0e12-11e6-9083-8b69d2e024fa.png)


PHP 7


<insert your phpfmt configuration and PHP related information>


```

**Comment by ccirello** [comment]
Please add `"debug": true` in the configuration file. I should like to know what's the underlying call. I could not reproduce this bug. It seems to be an interaction with some other plugin.

**Comment by aeyachts99** [comment]
I can still reproduce this bug.
What should have changed with the addition of the Debug option? Should there be some output somewhere?

My steps to reproduce are:
1. My code is 

echo '<pre>';
    print_r($my_array);
    echo '</pre>';

2. Save file.

3. Edit->Comment->Toggle Block Comment produces

/*	echo '<pre>';
	print_r($my_array);
	echo '</pre>';*/

4. Saving the file with the "format_on_save" option enabled results in:

	/*echo '<pre>';
		print_r($my_array);
	*/

**Comment by ccirello** [comment]
Yes, it will produce additional output in the console. Repeat the steps without using the toggle block comment. This option does not belong to phpfmt.

**Comment by aeyachts99** [comment]
If I repeat the steps without using the SublimeText “Toggle Block Comment” command then the issue does not happen but that is not part of my workflow. Applying phpfmt  "format on save" to a block comment is part of it and this is where the issue occurs.

However, I have just removed the package SublimeLinter and the issue no longer occurs so perhaps that package is doing something to contribute to the issue.
[http://www.aegraphics.tv/_assets/_mailsigs/logo_AE.jpg]<http://www.aegraphics.tv>
Andrew Turner  |  Web Development Manager  |  Alston Elliot Ltd

Mobile:  +44 7796 936454<tel:00447796936454>


[http://www.aegraphics.tv/_assets/_mailsigs/logo_twitter.jpg]<https://twitter.com/aegraphicstv>  [http://www.aegraphics.tv/_assets/_mailsigs/logo_linkedin.jpg] <http://www.linkedin.com/company/alston-elliot>
Alston Elliot Ltd. registered in England No. 2708449   VAT No.GB 596 274 39&

On 3 May 2016, at 13:05, C Cirello <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, it will produce additional output in the console. Repeat the steps without using the toggle block comment. This option does not belong to phpfmt.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/phpfmt/fmt/issues/139#issuecomment-216507978>

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________


______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by ccirello** [comment]
It is evident then that it is not phpfmt problem.
