### ISSUE TITLE
class implements list indention

### ISSUE THREAD

**Issue by dans98** [phpfmt/fmt#140]
Description:
[PSR-2](http://www.php-fig.org/psr/psr-2/) states the following:

> Lists of implements MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one interface per line.

If you format the implements list per the standard, when phpfmt runs, it un-indents the list.

Failing code:
```
<?php
namespace Vendor\Package;

class ClassName extends ParentClass implements
    \ArrayAccess,
    \Countable,
    \Serializable
{
    // constants, properties, methods
}
```

Expected result:
```
<?php
namespace Vendor\Package;

class ClassName extends ParentClass implements
    \ArrayAccess,
    \Countable,
    \Serializable
{
    // constants, properties, methods
}

```

Actual result:
```
<?php
namespace Vendor\Package;

class ClassName extends ParentClass implements
\ArrayAccess,
\Countable,
\Serializable
{
    // constants, properties, methods
}
```

Your configuration:
```
PHP 7.0.6

{
	"format_on_save": true,
	"passes":
	[
		"ReindentSwitchBlocks"
	],
	"php55compat": true,
	"php_bin": "php",
	"psr1": true,
	"psr2": true,
	"version": 4
}
```

**Comment by ccirello** [comment]
Can you provide a fix for this?

**Comment by dans98** [comment]
Unfortunately I'm not familiar enough phpfmt & it's methodologies to provide a fix. 

I just noticed this while I was saving a file in sublime this evening. It's probably a pretty rare scenario, unless you are implementing several interfaces from namespaces with long names.

**Comment by ccirello** [comment]
@dans98 please upgrade to https://github.com/phpfmt/fmt/releases/tag/20.4.0

**Comment by dans98** [comment]
I upgraded, and that fixed the case i listed initially.

I did notice 2 things though.

1. if I go to the command pallet and run troubleshoot information, it's still claiming 20.3.0
2. If I use bracketed namespaces like the following it still un-indents the list.

Failing code:
```
<?php
namespace Vendor\Package {

    class ClassName extends ParentClass implements
    	\ArrayAccess,
    	\Countable,
    	\Serializable
    {
        // constants, properties, methods
    }
}
```

Expected result:
```
<?php
namespace Vendor\Package {

    class ClassName extends ParentClass implements
    	\ArrayAccess,
    	\Countable,
    	\Serializable
    {
        // constants, properties, methods
    }
}
```

Actual result:
```
<?php
namespace Vendor\Package {

    class ClassName extends ParentClass implements
    \ArrayAccess,
    \Countable,
    \Serializable
    {
        // constants, properties, methods
    }
}
```

**Comment by ccirello** [comment]
Are you using Windows?

**Comment by dans98** [comment]
Yes, I'm using windows.

**Comment by ccirello** [comment]
That's why you're lacking the update... I don't personally maintain the windows plugin anymore. I am still waiting someone to step up and help with Windows version. As soon as someone takes it over this update will be released.
