### ISSUE TITLE
The code style

### ISSUE THREAD

**Issue by xiaomalover** [phpfmt/fmt#145]
According to psr2:

There MUST be one blank line after the namespace declaration, and there MUST be one blank line after the block of use declarations.

Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.

Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.

Psr code style should like following.
![ftj5ka u onuv e0jgz18g](https://cloud.githubusercontent.com/assets/10594451/15283622/89c938a2-1b7e-11e6-9e3e-9985f225612c.png)

But when I use phpfmt . the result like this 

![c 5k7 n _7vq z 3u4f](https://cloud.githubusercontent.com/assets/10594451/15283666/f2102dd0-1b7e-11e6-94e5-b61c5a9098d8.png)

**Comment by ccirello** [comment]
Use psr2 flag.
