### ISSUE TITLE
how to ignore file format in sublime text？

### ISSUE THREAD

**Issue by kcloze** [phpfmt/fmt#146]
Description:
I cant not ignore file with sublime text

Failing code:
```
    "ignore":["XHttp.php","extensions"],
    "exclude":["extensions"],

```

**Comment by ccirello** [comment]
Use `ignore_list`.

**Comment by kcloze** [comment]
Thanks, but I can not find it in documents,where is the ducuments?

**Comment by ccirello** [comment]
Someone has to write it still. PRs are welcome.
