### ISSUE TITLE
Warning PHP 7.0 or newer is required

### ISSUE THREAD

**Issue by cloudbps** [phpfmt/fmt#147]
Description

Warning.
PHP 7.0 or newer is required.
Please, upgrade your local PHP installation.
Debug information:phpfmt (php version):
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Your configuration:
phpfpm
{
"version": 4,
// "php_bin":"/usr/local/bin/php",
// "format_on_save":true,
"option": "value"
}
OS: ubuntu 14.04
PHP:5.5.9

I do not want to upgrade to php7, it can solve this warring ？

**Comment by ccirello** [comment]
You can install a standalone PHP 7.0 just to run the program.
