### ISSUE TITLE
the notwork reason is sublime's python is 3

### ISSUE THREAD

**Issue by adrianceding** [phpfmt/fmt#148]
sublime use python 3
when check update

if version == "":
        releaseJSON = urllib.request.urlopen("https://raw.githubusercontent.com/phpfmt/releases/master/releases.json").read()
        releases = json.loads(releaseJSON.decode('utf-8'))
        version = releases[channel]

throw urllib is not defined

the solution is add

import json
import urllib.request

in phpfmt.py
it working normal

**Comment by ccirello** [comment]
Upgrade to latest release.
