### ISSUE TITLE
phpfmt format_on_save is not working after update this morning

### ISSUE THREAD

**Issue by kcloze** [phpfmt/fmt#149]
Description:
phpfmt with sublime text is not working

Failing code:
```
# phpfmt's engine will no longer be bundled with the plugin.

From this release, the plugin will download from the phpfmt website the desired
version of the engine. It means you can pin the formatter engine into a particular
version should you want to.

In the configuration file, two new options have been added:


{
	...
	"engine_channel": "lts", // being lts or alpha
	"engine_version": "", // the version number within the channel, such as 803.2 - leave empty to upgrade to the latest always.
	...
}


```

**Comment by shamloo** [comment]
i have problem also,all settings are okay,plug-in does not work at all.
SublimeText3 / 7.0.4-7ubuntu2

**Comment by Sotiris-k** [comment]
Same here. This is the error that I see in the console
`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 674, in run
    src = dofmt(self, self.view, None, src, True)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 240, in dofmt
    p.stdin.write(src.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by ccirello** [comment]
@kcloze confirm whether you're using sublime-phpfmt-for-windows? 

@shamloo provide more context in a new issue, specific for Linux, not this one. 

@Sotiris-k it seems some file is missing. Try downloading the phar file from releases repository.

**Comment by shamloo** [comment]
@ccirello problem solved by adding  fmt.phar ,fmt.php folder to the OS path.

**Comment by ccirello** [comment]
OK. For those using windows, try upgrading to https://github.com/phpfmt/sublime-phpfmt-for-windows/releases/tag/13.0.1
