### ISSUE TITLE
not working on php7

### ISSUE THREAD

**Issue by QiiSyhx** [phpfmt/fmt#150]
php version
PHP 7.0.0alpha1 (cli) (built: Jun 24 2015 15:09:12)
os:windows 7 64bit home basic

it not working.
when i change a newest php,it is working.
PHP 7.0.6 (cli) (built: Apr 28 2016 13:46:50) ( ZTS )

**Comment by ccirello** [comment]
Good. PHP 7 is mandatory for this plugin.
