### ISSUE TITLE
Fails to format Doctrine docblocks

### ISSUE THREAD

**Issue by manticorp** [phpfmt/fmt#151]
Description:
PHP Fatal error:  Uncaught TypeError: substr() expects parameter 3 to be integer, boolean given in phar://<path>/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php

Failing code:
```
<?php

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="option")
 */
class Option
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;
}
```

Expected result:

Formatted result

Actual result:

Error shown above

Your configuration:

    "PrettyPrintDocBlocks",

It seems to struggle pretty printing Doctrine Entity docblocks, even though it's supported, see: https://phpdoc.org/docs/latest/guides/docblocks.html

> **Annotations**
> 
> In addition to the above you might also encounter Annotations when viewing DocBlocks. An Annotation is a specialized form of tag that not only documents a specific aspect of the associated element but also influences the way the application behaves.
> 
> Annotations come in various forms, many look exactly like normal tags but some have a more complicated syntax:
> ```
> /**
>  * @ORM\Entity(repositoryClass="MyProject\UserRepository")
>  */
> ```
> In the example above we demonstrate how you define that a class represents a database entity in Doctrine; as you can see the tag name is separated into two parts, a namespace and the actual annotation name,

**Comment by ccirello** [comment]
I am not sure how mentioning phpdoc relates to phpfmt. But it does seem like a bug to me.

**Comment by ccirello** [comment]
Upgrade to 803.4. In User's phpfmt configuration file:
```
{
	...
	"engine_channel": "lts", // being lts or alpha
	"engine_version": "803.4",
	...
}

```
